language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar

matrix:
  allow_failures:
    - php: hhvm
fast_finish: true