<?php
/**
 * Copyright (c) 2019 - present
 * laravel-updown - UpDownCheckTest.php
 * author: Roberto Belotti - roby.belotti@gmail.com
 * web : robertobelotti.com, github.com/biscolab
 * Initial version created on: 28/2/2019
 * MIT license: https://github.com/biscolab/laravel-updown/blob/master/LICENSE
 */

namespace Biscolab\LaravelUpDown\Tests;

use Biscolab\UpDown\Objects\Check;

/**
 * Class UpDownCheckTest
 * @package Biscolab\LaravelUpDown\Tests
 */
class UpDownCheckTest extends TestCase
{

    /**
     * @test
     */
    public function testCheckMethodReturnsCheckObject()
    {

        $this->assertInstanceOf(Check::class, updown()->Check());
    }

    /**
     * @test
     */
    public function testCheckMethodWithTokenReturnsCheckObjectWithTokenAsId()
    {
        /** @var Check $check */
        $check = updown()->Check(env('DEFAULT_TOKEN', 'DEFAULT_TOKEN'));
        $this->assertEquals(env('DEFAULT_TOKEN', 'DEFAULT_TOKEN'), $check->getId());
    }

    /**
     * @return void
     */
    public function setUp(): void
    {

        parent::setUp(); // TODO: Change the autogenerated stub

    }
}