<?php
/**
 * Copyright (c) 2019 - present
 * laravel-updown - UpDownTestp
 * author: Roberto Belotti - roby.belotti@gmail.com
 * web : robertobelotti.com, github.com/biscolab
 * Initial version created on: 15/2/2019
 * MIT license: https://github.com/biscolab/laravel-updown/blob/master/LICENSE
 */

namespace Biscolab\LaravelUpDown\Tests;

use Biscolab\UpDown\Objects\Check;
use Biscolab\UpDown\Objects\Event;
use Biscolab\UpDown\Objects\Node;
use Biscolab\UpDown\Objects\WebHook;

/**
 * Class UpDownTest
 * @package Biscolab\LaravelUpDown\Tests
 */
class UpDownTest extends TestCase
{

    /**
     * @test
     */
    public function testGetUpDownApiKey()
    {

        $this->assertEquals(updown()->getUpDown()->getKey(), env('API_KEY', 'API_KEY'));
    }

    /**
     * @test
     */
    public function testCheckMethodReturnsCheckObject()
    {

        $this->assertInstanceOf(Check::class, updown()->Check());
    }

    /**
     * @test
     */
    public function testNodeMethodReturnsNodeObject()
    {

        $this->assertInstanceOf(Node::class, updown()->Node());
    }

    /**
     * @test
     */
    public function testWebHookMethodReturnsWebHookObject()
    {

        $this->assertInstanceOf(WebHook::class, updown()->WebHook());
    }

    /**
     * @test
     */
    public function testEventMethodReturnsEventObject()
    {

        $this->assertInstanceOf(Event::class, updown()->Event());
    }

    /**
     * @return void
     */
    public function setUp(): void
    {

        parent::setUp(); // TODO: Change the autogenerated stub

    }
}