<?php
/**
 * Copyright (c) 2019 - present
 * laravel-updown - UpDownWebHookTest.php
 * author: Roberto Belotti - roby.belotti@gmail.com
 * web : robertobelotti.com, github.com/biscolab
 * Initial version created on: 28/2/2019
 * MIT license: https://github.com/biscolab/laravel-updown/blob/master/LICENSE
 */

namespace Biscolab\LaravelUpDown\Tests;

use Biscolab\UpDown\Objects\WebHook;

/**
 * Class UpDownWebHookTest
 * @package Biscolab\LaravelUpDown\Tests
 */
class UpDownWebHookTest extends TestCase
{

    /**
     * @test
     */
    public function testWebHookMethodReturnsWebHookObject()
    {

        $this->assertInstanceOf(WebHook::class, updown()->WebHook());
    }

    /**
     * @return void
     */
    public function setUp(): void
    {

        parent::setUp(); // TODO: Change the autogenerated stub

    }
}