<?php
/**
 * Copyright (c) 2019 - present
 * laravel-updown - UpDownNodeTest.php
 * author: Roberto Belotti - roby.belotti@gmail.com
 * web : robertobelotti.com, github.com/biscolab
 * Initial version created on: 28/2/2019
 * MIT license: https://github.com/biscolab/laravel-updown/blob/master/LICENSE
 */

namespace Biscolab\LaravelUpDown\Tests;

use Biscolab\UpDown\Objects\Node;

/**
 * Class UpDownNodeTest
 * @package Biscolab\LaravelUpDown\Tests
 */
class UpDownNodeTest extends TestCase
{

    /**
     * @test
     */
    public function testNodeMethodReturnsNodeObject()
    {

        $this->assertInstanceOf(Node::class, updown()->Node());
    }

    /**
     * @return void
     */
    public function setUp(): void
    {

        parent::setUp(); // TODO: Change the autogenerated stub

    }
}